struct.c File Reference
#include `struct.h`
*
Functions
alien * generate_alien (char *type, int height, int rank)
Generate an aliens from parameters.
alien * generate_random_alien ()
Generate a random alien with random type, height and rank.
void print_alien (alien *a)
Print out an alien.
char * generate_random_string (size_t length)
Generate a random string of length.
int generate_random_int (int min, int max)
Generate a random number in range.
alien ** generate_alien_count (size_t count)
Make an array of random aliens with a given size count.
void print_alien_count (alien **arr, size_t count)
Print an array of structs.
alien ** alien_shallow_copy (alien **src, size_t count)
Shallow copy an array of pointers to struct.
void alien_free (alien **a, size_t count)
Free an array of pointers to alien.
alien ** alien_deep_copy (alien **a, size_t count)
Deep copy an array of pointers of struct.
Function Documentation
alien** alien_deep_copy (alien ** a, size_t count)
Deep copy an array of pointers of struct.
Parameters
a Source array to copy from
count Length of the array
Returns
Deep copy of the array
References generate_alien().
Referenced by main().
void alien_free (alien ** a, size_t count)
Free an array of pointers to alien.
Parameters
a Array to free.
count Length of the array.
Referenced by main().
alien** alien_shallow_copy (alien ** src, size_t count)
Shallow copy an array of pointers to struct.
Parameters
src Source array to copy from.
count Length of the array.
Returns
Shallow copy of the array.
Referenced by main().
alien* generate_alien (char * type, int height, int rank)
Generate an aliens from parameters.
Parameters
type Type of alien.
height Height of alien.
rank Rank of invading aliens.
Returns
Pointer to newly built alien.
References alien::height, mystrlen(), mystrndup(), alien::rank, and alien::type.
Referenced by alien_deep_copy(), and main().
alien** generate_alien_count (size_t count)
Make an array of random aliens with a given size count.
Parameters
n The number of elements in array.
Returns
A pointer to randomized array of aliens.
References generate_random_alien().
Referenced by main().
alien* generate_random_alien ()
Generate a random alien with random type, height and rank.
Returns
Randomized alien.
References generate_random_int(), generate_random_string(), alien::height, mystrlen(), mystrndup(), alien::rank, and alien::type.
Referenced by generate_alien_count(), and main().
int generate_random_int (int min, int max)
Generate a random number in range.
Parameters
min Min randomized value .
max Max randomized value.
Returns
Randomized number in range (min, max).
Referenced by generate_random_alien().
char* generate_random_string (size_t length)
Generate a random string of length.
Parameters
length Max length of string.
Returns
Randomized string.
Referenced by generate_random_alien().
void print_alien (alien * a)
Print out an alien.
Parameters
a The alien to print out.
References alien::height, alien::rank, and alien::type.
Referenced by main(), and print_alien_count().
void print_alien_count (alien ** arr, size_t count)
Print an array of structs.
Parameters
arr Array to print out.
count Number of elements in array.
References print_alien().
Referenced by main().